package com.orcchg.yandexcontest.infra.libraries

object Versions {
    const val appCompat = "1.2.0"
    const val appStartup = "1.0.0"
    const val autoDispose = "1.4.0"
    const val buildToolsVersion = "30.0.0"
    const val chucker = "3.4.0"
    const val constraintLayout = "2.0.0-rc1"
    const val coreKtx = "1.3.1"
    const val dagger = "2.34.1"
    const val detekt = "1.16.0"
    const val espresso = "3.2.0"
    const val finnhub = "1.2.0"
    const val fragmentKtx = "1.3.2"
    const val glide = "4.12.0"
    const val gradleAndroid = "4.1.3"
    const val hamcrest = "1.3"
    const val javaBuildConfig = "1.1.8"
    const val javaxInject = "1"
    const val junit = "4.13.2"
    const val junitAndroidExt = "1.1.1"
    const val ktlint = "0.39.0"
    const val ktlintGradle = "9.4.1"
    const val ktStdLib = "1.4.32"
    const val leakCanary = "2.7"
    const val lifecycle = "2.3.1"
    const val lint = "27.0.1"
    const val material = "1.3.0"
    const val moshi = "1.12.0"
    const val navigation = "2.3.5"
    const val okHttp = "4.8.1"
    const val recyclerView = "1.2.0"
    const val retrofit = "2.9.0"
    const val room = "2.2.6"
    const val rx = "2.2.21"
    const val rxAndroid = "2.1.1"
    const val rxBinding = "3.1.0"
    const val rxKt = "2.4.0"
    const val scarlet = "0.1.12"
    const val shimmer = "0.5.0"
    const val spotless = "5.12.1"
    const val stetho = "1.6.0"
    const val swipeRefreshLayout = "1.1.0"
    const val versionsPlugin = "0.38.0"
    const val viewPager2 = "1.0.0"
    const val timber = "4.7.1"
}
